/*! Fighter class
*  The game rules used to implement the Fighter class are the following:
- Initial stats are generated by rolling 3d6
- A fighter hit point is calculated based on the characters level and constitution
- Fighter receive bonus attack based on level and strength
-- A character receive +1 per level
- Items that can be equipped: helmet, armor, shield, ring, belt, boots, weapon
* The reason why Fighter inherits from Character is because all characters in this game contains
a name and level and each class has specific modifier
*/

#pragma once
#include <iostream>
#include "Active.h"

using namespace std;


class Fighter : public Active
{
public:
	Fighter();
	~Fighter();
	Fighter(string name, string description, int level);
	void interact();
	void move(int x, int y);

	void Serialize(CArchive& archive);
	DECLARE_SERIAL(Fighter);
};
